# Generated by Django 3.2.7 on 2021-09-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('name2', models.CharField(blank=True, max_length=20, verbose_name='Segundo Nombre')),
                ('lname', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('lname2', models.CharField(blank=True, max_length=20, verbose_name='Apellido Materno')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
